# Website settings
url: "https://ajikodajis.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    music: "/music"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    
# Bio settings
name: "ajikodajis"
description: "The home page of ajikodajis"
thumbnail_path: "profile-photos/ajikodajis.png"
# bitcoin_address: ""
website_repo_url: "https://github.com/ajikodajis/ajikodajis.github.io"


# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/shaswotsatya"
    label: "Twitter"
    icon: "twitter-square"
    username: "@shaswotsatya"
  linkedin:
    url: "www.linkedin.com/in/shaswot-sm"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/shaswot.sm"
    label: "Facebook"
    icon: "facebook-square"
#   slideshare:
#     url: "https://www.slideshare.net/brikis98"
#     label: "SlideShare"
#     icon: "slideshare"
  github:
    url: "https://github.com/ajikodajis/"
    label: "GitHub"
    icon: "github-square"
#   email:
#     url: "mailto:jim@ybrikman.com"
#     label: "Email"
#     value: "jim@ybrikman.com"
#     icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Japan/Tokyo'
repository: ajikodajis/ajikodajis.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
